# Generated by Django 5.2.7 on 2025-10-29 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('backstory', models.TextField()),
                ('trait', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('interesting', models.TextField(default='Sin descripción', help_text='Intereses del personaje para abordar mas la historia')),
                ('personality', models.TextField(default='sin definir', help_text='Personalidad')),
                ('is_friend', models.IntegerField(default=20, help_text='Puntos necesarios para considerarse amigo')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(help_text='Nombre de la location', max_length=50, unique=True)),
                ('descriptions', models.TextField(help_text='Descripcion de la situacion al llegar al juego', max_length=500)),
                ('imagen_fondo', models.URLField(blank=True, help_text='URl de las imagenes', null=True)),
                ('day_location', models.IntegerField(default=1, help_text='Asignacion de las situaciones')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
                'ordering': ['day_location', 'locations'],
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Para saber el dialogo')),
                ('decision_point', models.BooleanField(default=False, help_text='Para comprobar si lo de alante es un dialogo o no')),
                ('lines_type', models.CharField(choices=[('narration', 'Narración'), ('came_thought', 'Pensamiento de Came (Came*:)'), ('came_speech', 'Came habla'), ('npc_speech', 'NPC habla'), ('system', 'Mensaje del sistema')], default='narration', max_length=200)),
                ('orden', models.IntegerField(default=0, help_text='Orden en que aparecen en la linea de texto')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='TBL.character')),
            ],
            options={
                'verbose_name': 'Línea de Diálogo',
                'verbose_name_plural': 'Líneas de Diálogo',
                'ordering': ['situation', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_choice', models.CharField(default='Sin definir', max_length=300)),
                ('consequence', models.TextField(help_text='para saber que pasa despues')),
                ('order', models.IntegerField(default=0)),
                ('type_choice', models.CharField(choices=[('buena', 'Decisión Buena'), ('mala', 'Decisión Mala'), ('intermedia', 'Decisión Intermedia'), ('neutral', 'Decisión Neutral')], default='Sin definir', max_length=20)),
                ('friendship_points', models.IntegerField(default=0, help_text='Puntos que suma/resta a la relación con el NPC (+10 buena, -5 mala, 0 neutral)')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TBL.dialogue')),
                ('next_dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice', to='TBL.dialogue')),
            ],
            options={
                'verbose_name': 'Opción de Decisión',
                'verbose_name_plural': 'Opciones de Decisión',
                'ordering': ['dialogue', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Prologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='El comienzo de una nueva vida', help_text='Para el titulo del juego', max_length=200)),
                ('orden', models.IntegerField(help_text='Aca quiero lo del orden de aparacion de la cinematicas', unique=True)),
                ('text_prologo', models.TextField(help_text='Texto que aparecera en la pantalla')),
                ('content_dialogue', models.CharField(choices=[('narration', 'Narración'), ('dialogue', 'Diálogo (Mamá, Álex, etc.)'), ('came_thought', 'Pensamiento de Came')], max_length=200)),
                ('character', models.ForeignKey(blank=True, help_text='Personaje que habla (si es diálogo)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TBL.character')),
            ],
            options={
                'verbose_name': 'Prólogo',
                'verbose_name_plural': 'Prólogos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Situations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre de la situacion', max_length=20)),
                ('day', models.IntegerField(help_text='Numero de situacion en la que me encuentro', unique=True)),
                ('contexto_situation', models.TextField(help_text='Para hacer el contexto de la situacion en la que se encuentra')),
                ('is_gameplay', models.BooleanField(default=True, help_text='Campo para saber si es jugable')),
                ('orden_dialogue', models.IntegerField(default=0, help_text='Lineas de dialogo del day')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='TBL.character')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='TBL.location')),
            ],
            options={
                'verbose_name': 'Situación',
                'verbose_name_plural': 'Situaciones',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='dialogue',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='TBL.situations'),
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Kove', help_text='Nombre a su jugador', max_length=50)),
                ('select_conditions', models.CharField(choices=[('TEA', 'Trastorno del Espectro Autista'), ('DOWN', 'Síndrome de Down'), ('ADHD', 'TDAH'), ('OTHER', 'Otra')], default='TEA', help_text='Seleccione la condicion de su personaje (default:TEA)', max_length=50)),
                ('situation', models.IntegerField(default=1, help_text='Primera situacion del game')),
                ('situation_complet', models.BooleanField(default=False, help_text='Cuando complete la sitaucion del primer dia')),
                ('friend', models.IntegerField(default=0, help_text='Cantidad de amigos')),
                ('friend_counts', models.IntegerField(default=0, help_text='Cantidad de amigos al final')),
                ('final', models.BooleanField(default=False, help_text='Cuando completo todos los dias es TRUE')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Username', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de jugador',
                'verbose_name_plural': 'Perfiles de jugadores',
            },
        ),
        migrations.CreateModel(
            name='History_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Para saber cuando tomo las decisiones')),
                ('points_earned', models.IntegerField(help_text='Puntos de amistad que ganó/perdió con esta decisión')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='TBL.choice')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBL.situations')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='TBL.username')),
            ],
            options={
                'verbose_name': 'Historial de Decisión',
                'verbose_name_plural': 'Historial de Decisiones',
            },
        ),
        migrations.CreateModel(
            name='NPCRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_points', models.IntegerField(default=0, help_text='Puntos de amistad acumulados con este NPC')),
                ('is_friend', models.BooleanField(default=False, help_text='True si friendship_points >= character.friendship_threshold')),
                ('knows_condition', models.BooleanField(default=False, help_text='Si este NPC sabe sobre la condición del jugador')),
                ('revealed_on_day', models.IntegerField(blank=True, help_text='En qué día el jugador reveló su condición a este NPC', null=True)),
                ('interactions_count', models.IntegerField(default=0, help_text='Cantidad de veces que interactuó con este NPC')),
                ('last_interaction', models.DateTimeField(blank=True, help_text='Última vez que interactuó con este NPC', null=True)),
                ('character', models.ForeignKey(help_text='Personaje NPC', on_delete=django.db.models.deletion.CASCADE, related_name='player_relationships', to='TBL.character')),
                ('player', models.ForeignKey(help_text='Perfil del jugador', on_delete=django.db.models.deletion.CASCADE, related_name='npc_relationships', to='TBL.username')),
            ],
            options={
                'verbose_name': 'Relación con NPC',
                'verbose_name_plural': 'Relaciones con NPCs',
                'unique_together': {('player', 'character')},
            },
        ),
    ]
