# Generated by Django 5.2.6 on 2025-09-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='confirm_password',
        ),
    ]
