# Generated by Django 5.2.7 on 2025-10-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['situation', 'order'], 'verbose_name': 'Línea de Diálogo', 'verbose_name_plural': 'Líneas de Diálogo'},
        ),
        migrations.RenameField(
            model_name='dialogue',
            old_name='orden',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='dialogue',
            old_name='lines_type',
            new_name='type_line',
        ),
    ]
