# Generated by Django 5.2.7 on 2025-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0002_alter_dialogue_options_rename_orden_dialogue_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situations',
            name='day',
            field=models.IntegerField(help_text='Numero de situacion en la que me encuentro'),
        ),
    ]
