# Generated by Django 5.2.7 on 2025-10-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0003_alter_situations_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='type_line',
            new_name='line_type',
        ),
    ]
