# Generated by Django 5.2.6 on 2025-10-19 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0003_character_dialogue_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(help_text='Nombre de la location', max_length=50, unique=True)),
                ('descriptions', models.TextField(help_text='Descripcion de la situacion al llegar al juego', max_length=500)),
                ('imagen_fondo', models.URLField(blank=True, help_text='URl de las imagenes', null=True)),
                ('day_location', models.IntegerField(default=1, help_text='Asignacion de las situaciones')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
                'ordering': ['day_location', 'locations'],
            },
        ),
        migrations.AlterModelOptions(
            name='username',
            options={'verbose_name': 'Perfil de jugador', 'verbose_name_plural': 'Perfiles de jugadores'},
        ),
        migrations.RemoveField(
            model_name='username',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='username',
            name='name',
        ),
        migrations.RemoveField(
            model_name='username',
            name='password',
        ),
        migrations.AddField(
            model_name='username',
            name='final',
            field=models.BooleanField(default=False, help_text='Cuando completo todos los dias es TRUE'),
        ),
        migrations.AddField(
            model_name='username',
            name='friend',
            field=models.IntegerField(default=0, help_text='Cantidad de amigos'),
        ),
        migrations.AddField(
            model_name='username',
            name='friend_counts',
            field=models.IntegerField(default=0, help_text='Cantidad de amigos al final'),
        ),
        migrations.AddField(
            model_name='username',
            name='player_name',
            field=models.CharField(default='Kove', help_text='Nombre a su jugador', max_length=50),
        ),
        migrations.AddField(
            model_name='username',
            name='select_conditions',
            field=models.CharField(choices=[('TEA', 'Trastorno del Espectro Autista'), ('DOWN', 'Síndrome de Down'), ('ADHD', 'TDAH'), ('OTHER', 'Otra')], default='TEA', help_text='Seleccione la condicion de su personaje (default:TEA)', max_length=50),
        ),
        migrations.AddField(
            model_name='username',
            name='situation',
            field=models.IntegerField(default=1, help_text='Primera situacion del game'),
        ),
        migrations.AddField(
            model_name='username',
            name='situation_complet',
            field=models.BooleanField(default=False, help_text='Cuando complete la sitaucion del primer dia'),
        ),
        migrations.AlterField(
            model_name='username',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Username', to=settings.AUTH_USER_MODEL),
        ),
    ]
