# Generated by Django 5.2.7 on 2025-11-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0004_rename_type_line_dialogue_line_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='Fecha y hora del guardado')),
                ('auto_save', models.BooleanField(default=True, help_text='Si fue guardado automáticamente o manual')),
                ('game_state_snapshot', models.JSONField(blank=True, help_text='Snapshot completo del estado del juego (útil para debugging)', null=True)),
                ('current_dialogue_line', models.ForeignKey(blank=True, help_text='Última línea de diálogo mostrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TBL.dialogue')),
                ('current_situation', models.ForeignKey(blank=True, help_text='Situación actual en la que está el jugador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TBL.situations')),
                ('player', models.ForeignKey(help_text='Perfil del jugador', on_delete=django.db.models.deletion.CASCADE, related_name='game_saves', to='TBL.username')),
            ],
            options={
                'verbose_name': 'Guardado de Partida',
                'verbose_name_plural': 'Guardados de Partidas',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
