# Generated by Django 5.2.7 on 2025-10-29 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0004_location_alter_username_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Personaje', 'verbose_name_plural': 'Personajes'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['dialogue', 'order'], 'verbose_name': 'Opción de Decisión', 'verbose_name_plural': 'Opciones de Decisión'},
        ),
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['situation', 'orden'], 'verbose_name': 'Línea de Diálogo', 'verbose_name_plural': 'Líneas de Diálogo'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='character',
            name='interesting',
            field=models.TextField(default='Sin descripción', help_text='Intereses del personaje para abordar mas la historia'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_friend',
            field=models.IntegerField(default=20, help_text='Puntos necesarios para considerarse amigo'),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.TextField(default='sin definir', help_text='Personalidad'),
        ),
        migrations.AddField(
            model_name='choice',
            name='friendship_points',
            field=models.IntegerField(default=0, help_text='Puntos que suma/resta a la relación con el NPC (+10 buena, -5 mala, 0 neutral)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_choice',
            field=models.CharField(default='Sin definir', max_length=300),
        ),
        migrations.AddField(
            model_name='choice',
            name='type_choice',
            field=models.CharField(choices=[('buena', 'Decisión Buena'), ('mala', 'Decisión Mala'), ('intermedia', 'Decisión Intermedia'), ('neutral', 'Decisión Neutral')], default='Sin definir', max_length=20),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='lines_type',
            field=models.CharField(choices=[('narration', 'Narración'), ('came_thought', 'Pensamiento de Came (Came*:)'), ('came_speech', 'Came habla'), ('npc_speech', 'NPC habla'), ('system', 'Mensaje del sistema')], default='Sin definir', max_length=200),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='orden',
            field=models.IntegerField(default='Sin definir', help_text='Orden en que aparecen en la linea de texto'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='consequence',
            field=models.TextField(help_text='para saber que pasa despues'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='dialogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TBL.dialogue'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice', to='TBL.dialogue'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='TBL.character'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='decision_point',
            field=models.BooleanField(default=False, help_text='Para comprobar si lo de alante es un dialogo o no'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='text',
            field=models.TextField(help_text='Para saber el dialogo'),
        ),
        migrations.CreateModel(
            name='Prologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='El comienzo de una nueva vida', help_text='Para el titulo del juego', max_length=200)),
                ('orden', models.IntegerField(help_text='Aca quiero lo del orden de aparacion de la cinematicas', unique=True)),
                ('text_prologo', models.TextField(help_text='Texto que aparecera en la pantalla')),
                ('content_dialogue', models.CharField(choices=[('narration', 'Narración'), ('dialogue', 'Diálogo (Mamá, Álex, etc.)'), ('came_thought', 'Pensamiento de Came')], max_length=200)),
                ('character', models.ForeignKey(blank=True, help_text='Personaje que habla (si es diálogo)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TBL.character')),
            ],
            options={
                'verbose_name': 'Prólogo',
                'verbose_name_plural': 'Prólogos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Situations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre de la situacion', max_length=20)),
                ('day', models.IntegerField(help_text='Numero de situacion en la que me encuentro', unique=True)),
                ('contexto_situation', models.TextField(help_text='Para hacer el contexto de la situacion en la que se encuentra')),
                ('is_gameplay', models.BooleanField(default=True, help_text='Campo para saber si es jugable')),
                ('orden_dialogue', models.IntegerField(default=0, help_text='Lineas de dialogo del day')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='TBL.character')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='TBL.location')),
            ],
            options={
                'verbose_name': 'Situación',
                'verbose_name_plural': 'Situaciones',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='History_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Para saber cuando tomo las decisiones')),
                ('points_earned', models.IntegerField(help_text='Puntos de amistad que ganó/perdió con esta decisión')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='TBL.choice')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='TBL.username')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBL.situations')),
            ],
            options={
                'verbose_name': 'Historial de Decisión',
                'verbose_name_plural': 'Historial de Decisiones',
            },
        ),
        migrations.AddField(
            model_name='dialogue',
            name='situation',
            field=models.ForeignKey(default='Sin definir', on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='TBL.situations'),
        ),
        migrations.CreateModel(
            name='NPCRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_points', models.IntegerField(default=0, help_text='Puntos de amistad acumulados con este NPC')),
                ('is_friend', models.BooleanField(default=False, help_text='True si friendship_points >= character.friendship_threshold')),
                ('knows_condition', models.BooleanField(default=False, help_text='Si este NPC sabe sobre la condición del jugador')),
                ('revealed_on_day', models.IntegerField(blank=True, help_text='En qué día el jugador reveló su condición a este NPC', null=True)),
                ('interactions_count', models.IntegerField(default=0, help_text='Cantidad de veces que interactuó con este NPC')),
                ('last_interaction', models.DateTimeField(blank=True, help_text='Última vez que interactuó con este NPC', null=True)),
                ('character', models.ForeignKey(help_text='Personaje NPC', on_delete=django.db.models.deletion.CASCADE, related_name='player_relationships', to='TBL.character')),
                ('player', models.ForeignKey(help_text='Perfil del jugador', on_delete=django.db.models.deletion.CASCADE, related_name='npc_relationships', to='TBL.username')),
            ],
            options={
                'verbose_name': 'Relación con NPC',
                'verbose_name_plural': 'Relaciones con NPCs',
                'unique_together': {('player', 'character')},
            },
        ),
    ]
