# Generated by Django 5.2.7 on 2025-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0005_gamesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='day',
            field=models.IntegerField(default=0, help_text='Dia en el que estoy'),
        ),
    ]
