# Generated by Django 5.2.7 on 2025-11-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0006_username_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_dialogue', to='TBL.dialogue'),
        ),
    ]
