# Generated by Django 5.2.7 on 2025-11-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0007_alter_choice_next_dialogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='situation',
            new_name='situation_id',
        ),
    ]
