# Generated by Django 5.2.7 on 2025-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0008_rename_situation_username_situation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='end_situation',
            field=models.BooleanField(default=False),
        ),
    ]
