# Generated by Django 5.2.7 on 2025-11-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0009_dialogue_end_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='end_situation',
        ),
    ]
