# Generated by Django 5.2.7 on 2025-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0010_remove_dialogue_end_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='situations',
            name='moraleja',
            field=models.TextField(blank=True, help_text='Para mostrar la moraleja de la situacion', null=True),
        ),
    ]
