# Generated by Django 5.2.7 on 2025-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBL', '0011_situations_moraleja'),
    ]

    operations = [
        migrations.AddField(
            model_name='situations',
            name='audio',
            field=models.URLField(default='sounds/mix-audio.MP3', help_text='Campo para poner las URL de las situaciones'),
        ),
    ]
